name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - geopandas
  - shapely
  - rasterio
  - rioxarray
  - pyarrow
  - scikit-learn
  - statsmodels
  - gdal
  - contextily
  - jupyterlab
  - ipykernel
  - fiona
  - pyproj
  - rich
  - tqdm
  - pip
